import localFont from "next/font/local";
import "./globals.css";
import { mediumFont } from "./fonts/fontWeigtht";

export const metadata = {
  title: "Momentum - Progress Tracking Software",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mediumFont.className}  antialiased`}>{children}</body>
    </html>
  );
}
